/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the API and its database are up */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the entities a reader at this chapter knows about */
        get: {
            parameters: {
                query: {
                    /** @description The last manga chapter the reader has read. Nothing revealed later is returned. */
                    cutoff: number;
                    kind?: "character" | "titan" | "event" | "location" | "faction" | "arc" | "memory";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                id: string;
                                /** @enum {string} */
                                kind: "character" | "titan" | "event" | "location" | "faction" | "arc" | "memory";
                                name: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One entity, as far as the reader knows it */
        get: {
            parameters: {
                query: {
                    /** @description The last manga chapter the reader has read. Nothing revealed later is returned. */
                    cutoff: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            /** @enum {string} */
                            kind: "character" | "titan" | "event" | "location" | "faction" | "arc" | "memory";
                            name: string;
                            names: {
                                name: string;
                                variants: string[];
                            }[];
                            description: string[];
                            revealedIn: number;
                            sources: (number | (number)[])[];
                            born?: {
                                date: {
                                    year: number;
                                    month?: number;
                                    day?: number;
                                } | {
                                    between: ({
                                        year: number;
                                        month?: number;
                                        day?: number;
                                    } | {
                                        year: number;
                                        month?: number;
                                        day?: number;
                                    })[];
                                };
                                /** @enum {string} */
                                certainty: "stated" | "inferred";
                                sources: (number | (number)[])[];
                                notes?: string;
                            } | null;
                            died?: {
                                date: {
                                    year: number;
                                    month?: number;
                                    day?: number;
                                } | {
                                    between: ({
                                        year: number;
                                        month?: number;
                                        day?: number;
                                    } | {
                                        year: number;
                                        month?: number;
                                        day?: number;
                                    })[];
                                };
                                /** @enum {string} */
                                certainty: "stated" | "inferred";
                                sources: (number | (number)[])[];
                                notes?: string;
                            } | null;
                            start?: {
                                date: {
                                    year: number;
                                    month?: number;
                                    day?: number;
                                } | {
                                    between: ({
                                        year: number;
                                        month?: number;
                                        day?: number;
                                    } | {
                                        year: number;
                                        month?: number;
                                        day?: number;
                                    })[];
                                };
                                /** @enum {string} */
                                certainty: "stated" | "inferred";
                                sources: (number | (number)[])[];
                                notes?: string;
                            } | null;
                            end?: {
                                date: {
                                    year: number;
                                    month?: number;
                                    day?: number;
                                } | {
                                    between: ({
                                        year: number;
                                        month?: number;
                                        day?: number;
                                    } | {
                                        year: number;
                                        month?: number;
                                        day?: number;
                                    })[];
                                };
                                /** @enum {string} */
                                certainty: "stated" | "inferred";
                                sources: (number | (number)[])[];
                                notes?: string;
                            } | null;
                            seq?: number | null;
                            /** @description Relationships visible at this chapter. */
                            connections: number;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph/neighborhood/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything within a few connections of an entity */
        get: {
            parameters: {
                query: {
                    /** @description The last manga chapter the reader has read. Nothing revealed later is returned. */
                    cutoff: number;
                    depth?: number;
                    /** @description A moment in world time (YYYY, YYYY-MM or YYYY-MM-DD). Missing month/day mean the 1st. */
                    at?: string;
                    categories?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            center: string;
                            nodes: {
                                id: string;
                                /** @enum {string} */
                                kind: "character" | "titan" | "event" | "location" | "faction" | "arc" | "memory";
                                name: string;
                                /** @description Only possibly present at `at` (its dates are approximate). */
                                uncertain: boolean;
                                depth: number;
                            }[];
                            edges: {
                                id: string;
                                source: string;
                                target: string;
                                type: string;
                                /** @enum {string} */
                                category: "structural" | "event" | "causal" | "paths";
                                uncertain: boolean;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The strongest chain of connections between two entities */
        get: {
            parameters: {
                query: {
                    /** @description The last manga chapter the reader has read. Nothing revealed later is returned. */
                    cutoff: number;
                    from: string;
                    to: string;
                    /** @description A moment in world time (YYYY, YYYY-MM or YYYY-MM-DD). Missing month/day mean the 1st. */
                    at?: string;
                    categories?: string;
                    /** @description Entities the path must not pass through. */
                    exclude?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description null when the two aren't connected in what the reader knows. */
                            path: {
                                cost: number;
                                nodes: {
                                    id: string;
                                    /** @enum {string} */
                                    kind: "character" | "titan" | "event" | "location" | "faction" | "arc" | "memory";
                                    name: string;
                                    /** @description Only possibly present at `at` (its dates are approximate). */
                                    uncertain: boolean;
                                }[];
                                edges: {
                                    id: string;
                                    source: string;
                                    target: string;
                                    type: string;
                                    /** @enum {string} */
                                    category: "structural" | "event" | "causal" | "paths";
                                    uncertain: boolean;
                                }[];
                            } | null;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events the reader knows about, in world or story order
         * @description `world` orders events by when they happened (docs/model/dates.md §4); `story` orders them by the chapter that reveals them (docs/model/spoilers.md §8). Events whose date isn't revealed yet come last in world order.
         */
        get: {
            parameters: {
                query: {
                    /** @description The last manga chapter the reader has read. Nothing revealed later is returned. */
                    cutoff: number;
                    order?: "world" | "story";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            order: "world" | "story";
                            items: {
                                id: string;
                                name: string;
                                /** @description The chapter where the reader learns of this event. */
                                revealedIn: number;
                                start: {
                                    date: {
                                        year: number;
                                        month?: number;
                                        day?: number;
                                    } | {
                                        between: ({
                                            year: number;
                                            month?: number;
                                            day?: number;
                                        } | {
                                            year: number;
                                            month?: number;
                                            day?: number;
                                        })[];
                                    };
                                    /** @enum {string} */
                                    certainty: "stated" | "inferred";
                                    sources: (number | (number)[])[];
                                    notes?: string;
                                } | null;
                                end: {
                                    date: {
                                        year: number;
                                        month?: number;
                                        day?: number;
                                    } | {
                                        between: ({
                                            year: number;
                                            month?: number;
                                            day?: number;
                                        } | {
                                            year: number;
                                            month?: number;
                                            day?: number;
                                        })[];
                                    };
                                    /** @enum {string} */
                                    certainty: "stated" | "inferred";
                                    sources: (number | (number)[])[];
                                    notes?: string;
                                } | null;
                                seq: number | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find entities by name, description or connection, optionally in a year
         * @description Every word must match the entity's names, a revealed description, or a connected entity's name. A standalone number (`850`) restricts to that year. Only what the reader has reached takes part in matching.
         */
        get: {
            parameters: {
                query: {
                    /** @description The last manga chapter the reader has read. Nothing revealed later is returned. */
                    cutoff: number;
                    q: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The words searched for. */
                            terms: string[];
                            /** @description The year searched in, if any. */
                            year: number | null;
                            items: {
                                id: string;
                                /** @enum {string} */
                                kind: "character" | "titan" | "event" | "location" | "faction" | "arc" | "memory";
                                name: string;
                                /** @enum {string} */
                                reason: "name" | "description" | "connection" | "year";
                                /** @description What matched: a name, a description paragraph, or a connected name. */
                                detail: string;
                                score: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
